[package]
name = "hawdevelopment/marchingsquares"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@^1"
Fission = "hawdevelopment/fission@0.1.0"